name: SBOM Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-sbom:
    name: Generate or Update SBOM
    runs-on: ubuntu-latest

    permissions: # Agrega esta sección
      contents: write # Habilita permisos de escritura

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Asegura que el token esté configurado
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install CycloneDX CLI
      run: npm install -g @cyclonedx/bom

    - name: Generate SBOM
      run: npx cyclonedx-bom -o sbom.json

    - name: Check for SBOM changes
      id: sbom-changes
      run: |
        if git diff --exit-code sbom.json; then
          echo "No changes in SBOM"
          echo "changed=false" >> $GITHUB_ENV
        else
          echo "SBOM has changes"
          echo "changed=true" >> $GITHUB_ENV
        fi

    - name: Commit and Push SBOM
      if: env.changed == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add sbom.json
        git commit -m "chore: update SBOM"
        git push

